spring.application.name=Scaffolding

server.port=8081

#spring.datasource.url=jdbc:mysql://localhost:3306/tesis_templarestaurante_prueba
#spring.datasource.username=root
#spring.datasource.password=admin
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



#JPA y Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
spring.servlet.multipart.max-file-size=20MB


# H2 consola web (opcional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# SQL initialization - �NUEVAS PROPIEDADES!
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true


# Email (SMTP) configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuracion de MercadoPago
mercadopago.access.token=
mercadopago.public.key=

# Precio de reserva VIP (en pesos argentinos)
reserva.vip.precio=5000.00


